### ISSUE TITLE
Variable height of slides

### ISSUE THREAD

**Issue by formmailer** [ekallevig/jShowOff#10]
Hi Erik,

I am not sure if this can be solved, but I'll ask you anyway:
The HTML parts I rotate using jshowoff have different heights. This works fine except for one little thing:
it displays all the content (multiple slides) for a (split)second before creating the actual slides. Is there a way to avoid this?

I can e-mail you the URL of my page if you want to see what I mean...

Thanks in advance,
//Jasper

**Comment by ekallevig** [comment]
Hey Jasper -- sorry for the delay.  If you can send me the url of your page to look at, I can see if there's an easy fix for your issue.

http://ekallevig.com/contact/

**Comment by ekallevig** [comment]
Ah I see what your issue is... one way to avoid it is to add style="display:none;" to all but the first 'slide' in your set.  Another way, if you happen to have a fixed height on your slides, is to set the same fixed height on the wrapper around the slides and then set overflow:hidden; on the wrapper.

**Comment by formmailer** [comment]
Wow, it was that easy.... now it works like a charm!
Thanks Erik!

**Comment by ekallevig** [comment]
Cheers!
