### ISSUE TITLE
Control MouseOut

### ISSUE THREAD

**Issue by pbarbalias** [ekallevig/jShowOff#17]
Whenever there is a mouseout event, immediately the next div is shown.
That is not so good if the user accidentally triggers mouseover and mouseout.

It would be nice to have it as an option, to turn it off.

**Comment by ekallevig** [comment]
You can disable this feature by setting the 'hoverPause' option to 'false'.  What happens when that is enabled (by default) is that you hover over the slide and it pauses, then resumes play when you mouseout.  I agree it can be jarring for accidental mouseovers, so I plan to fix that in a future release.

**Comment by pbarbalias** [comment]
Thank you very much for your immediate answer.
Indeed that fixed my problem. Great!

**Comment by errkk** [comment]
Or if you want to keep the hover pause functionality, but stop it from flickering you need to stop the hover event firing loads of times as the mouse moves over the carousel.  By adding the HoverIntent plugin, the flicker can be reduced.

if(config.hoverPause){$cont.hover(function()
in the minified source and change it for: 
if(config.hoverPause){$cont.hoverIntent(function()

http://cherne.net/brian/resources/jquery.hoverIntent.minified.js
