### ISSUE TITLE
Blocking other jquery functionality

### ISSUE THREAD

**Issue by drewbeta** [ekallevig/jShowOff#9]
Hello! great plug-in, but I'm having a little issue. I have a script that sets a rel on external links, and when an external link is clicked it triggers a modal pop-up asking if the user wants to leave. The script is not setting the rel on links within the jshowoff slideshow. Not a problem, I just set it manually. However, even with it set manually, the external link with the rel is not triggering the modal window. It seems like jshowoff is somehow blocking other jquery functionality within the slideshow. any Ideas? my eternal link script looks like this:

$(function(){
    var setLink;
    $('#external').dialog({
        autoOpen: false,
        height: 300,
        width: 350,
        modal: true,
        buttons: {
            'Continue to third party site': function(){
                window.open(setLink);
                $(this).dialog('close');
            },
            'Do not leave, close page': function(){
                $(this).dialog('close');
            }
        }
    });

```
$('a[href^="http://"]').attr("rel","externallink");
$('a[href^="https://"]').attr("rel","externallink");

$('a[rel="externallink"]').click(function(){
    $('#external').dialog('open');
    setLink = $(this).attr('href');
    return false;
}); 
```

});

Thanks for any help!

**Comment by ekallevig** [comment]
Hey -- not sure at first glance why there should be any conflict.  If you can get your page on a server I'd be happy to take a look at troubleshooting it :)

**Comment by drewbeta** [comment]
here is a skimmed-down version: http://www.alligatortek.com/test-script/
You'll see my script works on the link under the banner area, but not on links within the banner area.
thanks for your help

**Comment by drewbeta** [comment]
btw, I manually set the rel on the second banner, as I can see that the rel gets set on document load, at which time jshowoff removes the hidden banners (I'm guessing that's why the rel attributes are not getting set)

**Comment by ekallevig** [comment]
I think what's happening is that when the page loads, jshowoff stores all the slides in memory and removes them from the DOM, which is why the rel attributes aren't getting added.  Beyond that, the click event you're using only works if the element stays in the DOM, so there's a couple things to do here:
1. If you can, call the script that adds rel attributes BEFORE calling jshowoff -- that way the 'slides' jshowoff stores in memory will have the rel attributes.
2. Instead of using $().click() to trigger the dialog, use $().live('click') so that even new elements added to the DOM will trigger dialogs.

Let me know if that doesn't do it :)

**Comment by ekallevig** [comment]
I threw it up on my server with those changes and it did the trick.

http://ekallevig.com/demos/drewbeta/test.html

**Comment by drewbeta** [comment]
Thank you so much, it worked like a charm. You are a gentleman and a scholar!

**Comment by ekallevig** [comment]
Too kind, my good man!
